# frozen_string_literal: true

source "https://rubygems.org"

gemspec
#gem 'jekyll-maps'
gem "jekyll-loading-lazy"
gem "kramdown-parser-gfm"
gem "jekyll-seo-tag"
# gem 'jekyll-commonmark-ghpages'
# gem "jekyll-commonmark"
gem "webrick", "~> 1.7"
